import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Save, Send, Sparkles, Wand2, Image as ImageIcon, ChevronLeft } from 'lucide-react';
import toast from 'react-hot-toast';
import { bulkAPI } from '../api/client';
import LoadingSpinner from '../components/common/LoadingSpinner';
import PhotoGallery from '../components/common/PhotoGallery';
import SmartPricing from '../components/common/SmartPricing';
import ImageEditor from '../components/common/ImageEditor';
import type { Draft } from '../types';
import { motion } from 'framer-motion';
import { GlassCard } from '../components/ui/GlassCard';
import { Button } from '../components/ui/Button';

export default function DraftEdit() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [draft, setDraft] = useState<Draft | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [aiGenerating, setAiGenerating] = useState(false);
  const [editingImage, setEditingImage] = useState<string | null>(null);

  useEffect(() => {
    if (id) loadDraft(id);
  }, [id]);

  const loadDraft = async (draftId: string) => {
    try {
      const response = await bulkAPI.getDraft(draftId);
      setDraft(response.data);
    } catch (error) {
      setError('Failed to load draft');
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!draft || !id) return;

    setSaving(true);
    try {
      await bulkAPI.updateDraft(id, {
        title: draft.title,
        description: draft.description,
        price: draft.price,
        category: draft.category,
        condition: draft.condition,
        color: draft.color,
        brand: draft.brand,
        size: draft.size,
        sku: draft.sku,
        location: draft.location,
        stock_quantity: draft.stock_quantity,
      });
      toast.success('Draft saved successfully!');
    } catch (error: any) {
      toast.error(error.response?.data?.detail || 'Failed to save draft');
    } finally {
      setSaving(false);
    }
  };

  const handlePublish = async () => {
    if (!id || !confirm('Publish this draft to Vinted?')) return;

    setSaving(true);
    try {
      await bulkAPI.publishDraft(id);
      toast.success('Draft published successfully!');
      navigate('/drafts');
    } catch (error: any) {
      toast.error(error.response?.data?.detail || 'Failed to publish draft');
      setSaving(false);
    }
  };

  const handleAITitle = async () => {
    if (!draft) return;
    setAiGenerating(true);

    try {
      // Simulate AI generation - replace with actual API call
      await new Promise(resolve => setTimeout(resolve, 1500));
      const aiTitle = `${draft.brand} ${draft.category} ${draft.color} - Taille ${draft.size} - ${draft.condition}`;
      setDraft({ ...draft, title: aiTitle });
      toast.success('Title generated by AI!');
    } catch (error) {
      toast.error('Failed to generate title');
    } finally {
      setAiGenerating(false);
    }
  };

  const handleAIDescription = async () => {
    if (!draft) return;
    setAiGenerating(true);

    try {
      // Simulate AI generation - replace with actual API call
      await new Promise(resolve => setTimeout(resolve, 2000));
      const aiDescription = `Magnifique ${draft.category} de la marque ${draft.brand} en ${draft.color}.

État : ${draft.condition}. Cet article est en excellent état, très peu porté.

Caractéristiques :
- Taille : ${draft.size}
- Couleur : ${draft.color}
- Matière : 100% coton
- Style : Casual, parfait pour le quotidien

L'article a été très bien entretenu et ne présente aucun défaut visible.

Envoi soigné sous 24-48h 📦
N'hésitez pas si vous avez des questions !`;

      setDraft({ ...draft, description: aiDescription });
      toast.success('Description generated by AI!');
    } catch (error) {
      toast.error('Failed to generate description');
    } finally {
      setAiGenerating(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-8">
        <div className="max-w-7xl mx-auto">
          <GlassCard className="p-12">
            <div className="flex flex-col items-center justify-center space-y-4">
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                className="w-12 h-12 border-4 border-violet-500/30 border-t-violet-500 rounded-full"
              />
              <p className="text-slate-400">Loading draft...</p>
            </div>
          </GlassCard>
        </div>
      </div>
    );
  }

  if (error || !draft) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-8">
        <div className="max-w-7xl mx-auto">
          <GlassCard className="text-center py-12">
            <p className="text-red-400">{error || 'Draft not found'}</p>
          </GlassCard>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      {/* Header - Fixed */}
      <div className="bg-slate-900/50 backdrop-blur-xl border-b border-white/10 px-6 py-4 sticky top-0 z-10">
        <div className="flex items-center justify-between max-w-[1600px] mx-auto">
          <div className="flex items-center gap-4">
            <button
              onClick={() => navigate('/drafts')}
              className="p-2 text-slate-400 hover:text-white hover:bg-white/10 rounded-lg transition-all"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>
            <div>
              <h1 className="text-xl font-bold text-white">Edit Draft</h1>
              <p className="text-sm text-slate-400">
                Make any changes before publishing
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button
              onClick={handleSave}
              disabled={saving}
              variant="outline"
              icon={Save}
            >
              {saving ? 'Saving...' : 'Save'}
            </Button>
            <Button
              onClick={handlePublish}
              disabled={saving}
              icon={Send}
            >
              {saving ? 'Publishing...' : 'Publish'}
            </Button>
          </div>
        </div>
      </div>

      {/* Split Screen Layout */}
      <div className="flex-1 flex overflow-hidden max-w-[1600px] mx-auto w-full">
        {/* Left Panel - Photo Gallery (30%) */}
        <motion.div
          initial={{ x: -50, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          className="w-[30%] border-r border-white/10 bg-slate-900/30 overflow-y-auto"
        >
          <div className="p-6 space-y-4">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-semibold text-white">
                Photos ({draft.photos.length})
              </h3>
              <button
                className="text-xs text-violet-400 hover:text-violet-300 hover:underline flex items-center gap-1 transition-colors"
                onClick={() => {
                  if (draft.photos.length > 0) {
                    setEditingImage(draft.photos[0]);
                  }
                }}
              >
                <ImageIcon className="w-3 h-3" />
                Edit
              </button>
            </div>

            <PhotoGallery
              photos={draft.photos.map((url, index) => ({
                id: `photo-${index}`,
                url: url,
                order: index
              }))}
              onPhotosChange={async (newPhotos) => {
                const newPhotoUrls = newPhotos.map(p => p.url);
                setDraft({ ...draft, photos: newPhotoUrls });

                try {
                  await bulkAPI.reorderPhotos(id!, newPhotoUrls);
                } catch (error: any) {
                  toast.error('Failed to save photo order');
                }
              }}
              onPhotoAdd={async (files) => {
                try {
                  setSaving(true);
                  const fileArray = Array.from(files);
                  await bulkAPI.addPhotos(id!, fileArray);

                  const updatedDraft = await bulkAPI.getDraft(id!);
                  setDraft(updatedDraft.data);
                  toast.success(`${fileArray.length} photo(s) added!`);
                } catch (error: any) {
                  toast.error('Failed to add photos');
                } finally {
                  setSaving(false);
                }
              }}
              editable={true}
            />

            {/* Photo Tips */}
            <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg">
              <p className="text-xs font-medium text-gray-900 dark:text-white mb-2">
                📸 Photo Tips
              </p>
              <ul className="text-xs text-gray-600 dark:text-gray-400 space-y-1">
                <li>• First photo is the cover</li>
                <li>• Add 5-8 photos for best results</li>
                <li>• Use natural lighting</li>
                <li>• Show all angles & details</li>
              </ul>
            </div>
          </div>
        </motion.div>

        {/* Right Panel - Form (70%) */}
        <motion.div
          initial={{ x: 50, opacity: 0 }}
          animate={{ x: 0, opacity: 1 }}
          className="flex-1 overflow-y-auto bg-white dark:bg-gray-900"
        >
          <div className="max-w-3xl mx-auto p-6 space-y-6">
            {/* Title with AI Helper */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Title
                </label>
                <button
                  onClick={handleAITitle}
                  disabled={aiGenerating}
                  className="text-xs text-primary-600 dark:text-primary-400 hover:underline flex items-center gap-1"
                >
                  <Sparkles className="w-3 h-3" />
                  AI Generate
                </button>
              </div>
              <input
                type="text"
                value={draft.title}
                onChange={(e) => setDraft({ ...draft, title: e.target.value })}
                className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                maxLength={200}
                placeholder="Enter a catchy title..."
              />
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                {draft.title.length}/200 characters
              </p>
            </div>

            {/* Smart Pricing */}
            <SmartPricing
              category={draft.category}
              brand={draft.brand}
              condition={draft.condition}
              currentPrice={draft.price}
              onChange={(newPrice) => setDraft({ ...draft, price: newPrice })}
            />

            {/* Description with AI Helper */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
                  Description
                </label>
                <button
                  onClick={handleAIDescription}
                  disabled={aiGenerating}
                  className="text-xs text-primary-600 dark:text-primary-400 hover:underline flex items-center gap-1"
                >
                  <Wand2 className="w-3 h-3" />
                  AI Generate
                </button>
              </div>
              <textarea
                value={draft.description}
                onChange={(e) => setDraft({ ...draft, description: e.target.value })}
                className="w-full px-4 py-3 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors min-h-[200px] resize-y"
                maxLength={2000}
                placeholder="Describe your item in detail..."
              />
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                {draft.description.length}/2000 characters
              </p>
            </div>

            {/* Item Details Grid */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Category
                </label>
                <input
                  type="text"
                  value={draft.category}
                  onChange={(e) => setDraft({ ...draft, category: e.target.value })}
                  className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Condition
                </label>
                <select
                  value={draft.condition}
                  onChange={(e) => setDraft({ ...draft, condition: e.target.value })}
                  className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                >
                  <option value="Neuf avec étiquette">Neuf avec étiquette</option>
                  <option value="Neuf sans étiquette">Neuf sans étiquette</option>
                  <option value="Très bon état">Très bon état</option>
                  <option value="Bon état">Bon état</option>
                  <option value="Satisfaisant">Satisfaisant</option>
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Brand
                </label>
                <input
                  type="text"
                  value={draft.brand}
                  onChange={(e) => setDraft({ ...draft, brand: e.target.value })}
                  className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Color
                </label>
                <input
                  type="text"
                  value={draft.color}
                  onChange={(e) => setDraft({ ...draft, color: e.target.value })}
                  className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Size
                </label>
                <input
                  type="text"
                  value={draft.size}
                  onChange={(e) => setDraft({ ...draft, size: e.target.value })}
                  className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                />
              </div>
            </div>

            {/* Stock Management Section (Dotb feature) */}
            <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
              <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-4">
                📦 Stock Management
              </h3>
              <div className="grid grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    SKU
                  </label>
                  <input
                    type="text"
                    value={draft.sku || ''}
                    onChange={(e) => setDraft({ ...draft, sku: e.target.value })}
                    placeholder="e.g. NIKE-AM90-001"
                    className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                  />
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    Stock Keeping Unit
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Location
                  </label>
                  <input
                    type="text"
                    value={draft.location || ''}
                    onChange={(e) => setDraft({ ...draft, location: e.target.value })}
                    placeholder="e.g. Shelf A3, Box 12"
                    className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                  />
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    Physical storage
                  </p>
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Quantity
                  </label>
                  <input
                    type="number"
                    value={draft.stock_quantity || 1}
                    onChange={(e) => setDraft({ ...draft, stock_quantity: parseInt(e.target.value) || 1 })}
                    min="1"
                    className="w-full px-4 py-2 bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-colors"
                  />
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    In stock
                  </p>
                </div>
              </div>
            </div>
          </div>
        </motion.div>
      </div>

      {/* Image Editor Modal */}
      {editingImage && (
        <ImageEditor
          image={editingImage}
          onSave={(editedImage) => {
            // Handle saving edited image
            toast.success('Image edited successfully!');
            setEditingImage(null);
          }}
          onClose={() => setEditingImage(null)}
        />
      )}
    </div>
  );
}
